# Generated by Django 2.2.2 on 2019-06-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlitchedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Nome')),
                ('original_file', models.ImageField(upload_to='', verbose_name='Imagem original')),
                ('glitched_file', models.ImageField(upload_to='', verbose_name='Imagem vanellopelizada')),
                ('size', models.PositiveIntegerField(verbose_name='Tamanho da parte do arquivo a ser vanellipelizado')),
                ('times', models.PositiveIntegerField(verbose_name='Vezes em que o arquivo passará pela vanellopelização')),
            ],
        ),
    ]
